#!/bin/bash

# .aw/prepare-release.sh - Prepare a release locally
# This script switches to the dev branch, runs tests, bumps the version,
# updates the changelog, and creates a PR to main.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}== Preparing Release ==${NC}"

# 1. Ensure we are on the dev branch
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" != "dev" ]; then
  echo -e "${BLUE}Not on dev branch. Switching to dev...${NC}"
  git checkout dev
fi

# 2. Pull latest changes
echo -e "${BLUE}Pulling latest changes...${NC}"
git pull origin dev

# 3. Run prerelease checks
echo -e "${BLUE}Running prerelease checks...${NC}"
npm run lint
npm run format:check
npm test

# 4. Build to ensure everything is correct
echo -e "${BLUE}Building project...${NC}"
npm run build

# 5. Run semantic-release locally to upversion
# We use a temporary config to avoid NPM publishing locally
echo -e "${BLUE}Calculating next version and updating files...${NC}"

# Create a temporary config for local use
cat > .aw/releaserc.local.json <<EOF
{
  "branches": ["dev"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    ["@semantic-release/npm", { "npmPublish": false }],
    ["@semantic-release/git", {
      "assets": ["package.json", "CHANGELOG.md"],
      "message": "chore(release): v\${nextRelease.version} [skip ci]"
    }],
    "@semantic-release/github"
  ]
}
EOF

# GITHUB_TOKEN or GH_TOKEN is required by semantic-release to push tags and create GitHub releases.
# If not set, we'll try to use the one from gh cli if available.
if [ -z "$GITHUB_TOKEN" ] && [ -z "$GH_TOKEN" ]; then
  if command -v gh &> /dev/null; then
    export GITHUB_TOKEN=$(gh auth token)
  else
    echo -e "${RED}Error: GITHUB_TOKEN or GH_TOKEN is not set and gh CLI is not installed.${NC}"
    echo "Please set GITHUB_TOKEN to allow semantic-release to push tags and create releases."
    exit 1
  fi
fi

npx semantic-release --no-ci --config .aw/releaserc.local.json

# Cleanup temporary config
rm .aw/releaserc.local.json

# 6. Create PR from dev to main
if command -v gh &> /dev/null; then
  VERSION=$(node -p "require('./package.json').version")
  echo -e "${BLUE}Creating PR to main for version v$VERSION...${NC}"
  # Check if a PR already exists
  if gh pr list --base main --head dev --json number --jq '.[0].number' | grep -q '^[0-9]\+$'; then
    echo -e "${GREEN}PR already exists. Updating...${NC}"
  else
    gh pr create --base main --head dev --title "chore(release): v$VERSION" --body "Automated release PR generated by .aw/prepare-release.sh"
  fi
else
  echo -e "${RED}GitHub CLI (gh) not found.${NC} Please create a PR from dev to main manually."
fi

echo -e "${GREEN}Done! Once the PR is merged to main, the Publish workflow will trigger.${NC}"
