#!/bin/bash

# .aw/release-pre.sh - Prepare a release locally
# This script switches to the dev branch, runs tests, bumps the version,
# updates the changelog, and creates a PR to main.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}== 🚀 Preparing Release ==${NC}"

# 0. Ensure we are in the project root
if [ ! -f "package.json" ]; then
  echo -e "${RED}Error: package.json not found. Please run this script from the project root.${NC}"
  exit 1
fi

# 1. Ensure we are on the dev branch
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" != "dev" ]; then
  echo -e "${BLUE}Not on dev branch. Switching to dev...${NC}"
  git checkout dev
fi

# 2. Pull latest changes and tags
echo -e "${BLUE}Pulling latest changes and tags...${NC}"
git pull origin dev
git fetch --tags --force

# 3. Store old version to check for changes later
OLD_VERSION=$(node -p "require('./package.json').version")

# 4. Run prerelease checks
echo -e "${BLUE}Running prerelease checks...${NC}"
npm run lint
npm run format:check
npm test

# 5. Build to ensure everything is correct
echo -e "${BLUE}Building project...${NC}"
npm run build

# 6. Run semantic-release locally to upversion
echo -e "${BLUE}Calculating next version and updating files...${NC}"

# Check for tag conflicts. If the current version in package.json has a tag
# that is not reachable from the current branch, it will cause semantic-release to fail.
# This often happens after squash-merging a previous release.
CURRENT_JSON_VERSION=$(node -p "require('./package.json').version" 2>/dev/null || echo "0.0.0")
if [ "$CURRENT_JSON_VERSION" != "0.0.0" ] && git rev-parse "v$CURRENT_JSON_VERSION" >/dev/null 2>&1; then
  if ! git merge-base --is-ancestor "v$CURRENT_JSON_VERSION" HEAD; then
    echo -e "${YELLOW}Warning: Tag v$CURRENT_JSON_VERSION exists but is not reachable from HEAD.${NC}"
    echo -e "${BLUE}Moving local tag v$CURRENT_JSON_VERSION to HEAD to avoid conflict...${NC}"
    git tag -f "v$CURRENT_JSON_VERSION"
  fi
fi

# GITHUB_TOKEN or GH_TOKEN is required by semantic-release to push tags and create GitHub releases.
if [ -z "$GITHUB_TOKEN" ] && [ -z "$GH_TOKEN" ]; then
  if command -v gh &> /dev/null; then
    export GITHUB_TOKEN=$(gh auth token)
  else
    echo -e "${YELLOW}Warning: GITHUB_TOKEN or GH_TOKEN is not set and gh CLI is not installed.${NC}"
    echo "Please set GITHUB_TOKEN to allow semantic-release to push tags and create releases."
  fi
fi

npx semantic-release --no-ci

# 7. Get new version
VERSION=$(node -p "require('./package.json').version")

if [ "$OLD_VERSION" == "$VERSION" ]; then
  echo -e "${YELLOW}No version change detected (still v$VERSION).${NC}"
  echo "This usually means there are no new feature or fix commits since the last release."
  exit 0
fi

# 8. Create or update PR from dev to main
if command -v gh &> /dev/null; then
  echo -e "${BLUE}Extracting changelog for v$VERSION...${NC}"

  # Extract changelog for the new version
  # 1. Get the section for the current version
  # 2. Remove the version header itself
  # 3. Delete everything from the next version header onwards
  CHANGELOG_CONTENT=$(sed -n "/^#\{1,2\} \[$VERSION\]/,/^#\{1,2\} \[/p" CHANGELOG.md | grep -v "^#\{1,2\} \[$VERSION\]" | sed '/^#\{1,2\} \[/,$d')

  if [ -z "$(echo "$CHANGELOG_CONTENT" | tr -d '[:space:]')" ]; then
    # Fallback if extraction resulted in empty content
    CHANGELOG_CONTENT="* See CHANGELOG.md for full details."
  fi

  TITLE="chore(release): v$VERSION"

  # Create a temporary file for the PR body
  TEMP_BODY=$(mktemp)
  cat <<EOF > "$TEMP_BODY"
# 🚀 Release Preparation: v$VERSION

## 📦 What's New?
$CHANGELOG_CONTENT

## 🛠️ Automated Checks
- [x] Linting passed
- [x] Formatting checked
- [x] Tests passed
- [x] Build successful

## 🚦 Next Steps
1. Review the changes and the automated changelog.
2. Merge this PR into \`main\`.
3. The \`Publish\` workflow will automatically trigger on merge to \`main\`.

---
_Generated by \`.aw/release-pre.sh\`_
EOF

  echo -e "${BLUE}Creating/Updating PR to main for version v$VERSION...${NC}"

  # Check if a PR already exists
  PR_NUMBER=$(gh pr list --base main --head dev --json number --jq '.[0].number')

  if [ -n "$PR_NUMBER" ]; then
    echo -e "${GREEN}Existing PR #$PR_NUMBER found. Updating...${NC}"
    gh pr edit "$PR_NUMBER" --title "$TITLE" --body-file "$TEMP_BODY"
  else
    echo -e "${BLUE}Creating new PR...${NC}"
    # Use existing labels if they exist
    gh pr create --base main --head dev --title "$TITLE" --body-file "$TEMP_BODY" --label "released" --label "documentation"
  fi

  rm "$TEMP_BODY"
else
  echo -e "${RED}GitHub CLI (gh) not found.${NC} Please create a PR from dev to main manually."
  echo -e "Version is now ${GREEN}v$VERSION${NC}."
fi

echo -e "${GREEN}Done! Once the PR is merged to main, the Publish workflow will trigger.${NC}"
